server:
  port: 9999

notice: '公告：本工具用于英雄联盟玩家开黑寻找队友  <br/>    qq群：810322958'

admininfo:
  users:
    - name: 风车车的猫尾饼
      uid: 3027282745
      avatar: https://game.gtimg.cn/images/lol/act/img/profileicon/29.png

chatsetting:
  emoji:
    - title: '#icon--scared'
      data:
        - title: '#icon--astonished'
          text: 中毒