name: leaguetool-server Image CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    name: Build for Linux ARM64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-20.04]
        arch: [arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # 步骤名称
    - name: Set up JDK 8
      # 设置maven Java
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        # 启用缓存
        cache: maven
    - name: Build with Maven
      # 打包  这些步骤都是在工作目录下进行的 生成的jar文件在target下
      run: mvn -B package --file pom.xml
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        registry-mirror: https://register-docker.s6.design/v2/
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_REGISTER }}/leaguetool-server:linux_arm64
        platform: linux/arm64/v8
