name: leaguetool-server Image CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    name: Build for Linux ARM64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-20.04]
        arch: [arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_REGISTER }}/leaguetool-server:linux_arm64
        platform: linux/arm64/v8
